### ISSUE TITLE
Verificación de la calidad de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#10]
Evaluar la calidad de los datos recopilados para garantizar que sean adecuados para el análisis y modelado. Esto incluye identificar inconsistencias, valores faltantes, duplicados, y posibles errores en los datos.

**Comment by hepinedag** [comment]
Se verifico la calidad de los datos y los hallazgos encontrados fueron documentados en la memoria técnica
