### ISSUE TITLE
Selección de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#11]
Identificar y seleccionar las variables y registros relevantes del conjunto de datos disponibles, asegurando que sean adecuados para abordar los objetivos del negocio y el problema de minería de datos planteado.

**Comment by hepinedag** [comment]
En función de los resultados del análisis de calidad de datos ejecutado, se ha determinado remover las siguientes columnas de cada dataset:
Datos_creditos: no se realizan modificaciones al dataset.
Datos_tarjetas: se elimina la columna “nivel_tarjeta” por su alta correlación con el monto del límite de la misma.
