### ISSUE TITLE
Limpieza de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#12]
Garantizar la calidad de los datos, eliminando inconsistencias, valores incorrectos o datos irrelevantes que puedan afectar los análisis posteriores y la efectividad de los modelos.

**Comment by hepinedag** [comment]
En esta actividad se aplicaron filtros a nivel de filas de los datasets disponibles con base en las recomendaciones del experto en el dominio participante del proyecto y los resultados del análisis de calidad ejecutado en las tareas anteriores
