### ISSUE TITLE
Construcción de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#13]
Construir un conjunto de datos limpio, completo y estructurado que permita realizar análisis de manera efectiva, asegurando que la calidad y la integridad de los datos estén listas para el modelado.

**Comment by hepinedag** [comment]
Se realizan operaciones de transformaciónes sobre los datos en las siguientes columnas:
- estado_civil
- estado_credito
- edad
- antiguedad_empleado
- pct_ingreso
- ingresos
- tasa_interes
- antiguedad_cliente
- limite_credito_tc
- gastos_ult_12m
- operaciones_ult_12m
