### ISSUE TITLE
Integración de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#14]
Reunir los diferentes conjuntos de datos provenientes de diversas fuentes para consolidarlos en una estructura coherente y unificada.

**Comment by hepinedag** [comment]
Se ha llevado a cabo la integración de ambos conjuntos de datos utilizando el atributo "id_cliente" como clave de unión. El resultado de esta operación ha sido un nuevo conjunto de datos denominado "datos_integrados".
El resultado de estas operaciones fue el siguiente:
- Cantidad de filas: 9765
- Cantidad de columnas: 23
