### ISSUE TITLE
Formateo de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#15]
Preparar los datos para su análisis y modelado, asegurando que estén en el formato adecuado y sean coherentes para los pasos posteriores en el proyecto. Esto incluye tareas de limpieza, transformación y estructuración de los datos.

**Comment by hepinedag** [comment]
En este apartado se registran los metadatos del dataset resultante de las operaciones ejecutadas en esta fase de la metodología.  Además, se detallan los cambios de tipos de datos y la eliminación del atributo **id_cliente** al no ser necesario una vez integrado el dataset.
Estos cambios se han registrado en un nuevo archivo con el nombre **datos_final.csv**.
