### ISSUE TITLE
Obtener y exportar metadatos mediante una libreta

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#22]
La tarea consiste en identificar, recopilar y estructurar los metadatos asociados al conjunto de datos que será utilizado en el proyecto, asegurando que estén documentados de manera completa y precisa.

**Comment by hepinedag** [comment]
La tarea consistió en analizar un conjunto de datos para extraer y documentar metadatos relevantes. Se realizó una exploración inicial que incluyó la identificación de variables clave, tipos de datos, valores únicos, y problemas como valores ausentes o inconsistencias.
