### ISSUE TITLE
Redacción del informe final

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#30]
El propósito de esta etapa es documentar de manera exhaustiva y clara los hallazgos, procesos y resultados obtenidos durante todo el proyecto, asegurando que la información sea comprensible tanto para los equipos técnicos como para los tomadores de decisiones no técnicos. Este informe será la referencia principal del proyecto, demostrando el valor generado y ofreciendo recomendaciones basadas en el análisis.

**Comment by hepinedag** [comment]
Se exponen los resultados del modelo aplicado, evaluando su efectividad. El modelo se probó en datos no etiquetados relacionados con morosidad, midiendo su capacidad para identificar y predecir sin etiquetas previas.
