### ISSUE TITLE
Exploración de los datos

### ISSUE THREAD

**Issue by JonnHenry** [JonnHenry/13MBID_gestion_proyectos#9]
Realizar un análisis exploratorio para comprender las características básicas del conjunto de datos, evaluar su integridad y detectar valores atípicos, inconsistencias o patrones relevantes.

- [x] #22
- [x]  Documentar los resultados

**Comment by hepinedag** [comment]
Se ha realizado el análisis exploratorio para comprender las características básicas del conjunto de datos, evaluar su integridad y detectar valores atípicos, inconsistencias o patrones relevantes, los mismos fueron documentados en la memoria técnica.
